/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UnlvOeFeedbackButton {
        "buttonCss": object;
        "buttonText": string;
        "src": string;
    }
}
declare global {
    interface HTMLUnlvOeFeedbackButtonElement extends Components.UnlvOeFeedbackButton, HTMLStencilElement {
    }
    var HTMLUnlvOeFeedbackButtonElement: {
        prototype: HTMLUnlvOeFeedbackButtonElement;
        new (): HTMLUnlvOeFeedbackButtonElement;
    };
    interface HTMLElementTagNameMap {
        "unlv-oe-feedback-button": HTMLUnlvOeFeedbackButtonElement;
    }
}
declare namespace LocalJSX {
    interface UnlvOeFeedbackButton {
        "buttonCss"?: object;
        "buttonText"?: string;
        "src"?: string;
    }
    interface IntrinsicElements {
        "unlv-oe-feedback-button": UnlvOeFeedbackButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "unlv-oe-feedback-button": LocalJSX.UnlvOeFeedbackButton & JSXBase.HTMLAttributes<HTMLUnlvOeFeedbackButtonElement>;
        }
    }
}
